---
- name: "Create Hetzner CloudServer, runs only once afterwards root will be prohibited"
  hosts: cloudservers
  gather_facts: false
  user: "{{ deploy_user }}"
  roles:
    - { role: connection }
    - { role: secured_cloudserver }