---
- name: "Create Hetzner CloudServer, runs only once afterwards root will be prohibited"
  hosts: cloudservers
  gather_facts: false
  user: "{{ deploy_user }}"
  roles:
    - { role: preflight, tags: [ 'always' ] }
    - { role: connection, tags: [ 'always' ] }
    - { role: secured_cloudserver }