---
- name: "Make sure password for deploy_user variable is set"
  fail:
    msg: "Deploy user password is not set for {{ deploy_user }}"
  when: deploy_user_password is not defined

- name: "Create deployer group"
  group:
    name: "{{ deploy_user_group }}"
    state: present

- name: "Create deploy user {{ deploy_user }}"
  user:
    name: "{{ deploy_user }}"
    shell: /bin/bash
    password: "{{ deploy_user_password | password_hash('sha512') }}"
    update_password: always
    groups: "{{ deploy_user_group }}"
    state: present

- name: "Add authorized key to {{ deploy_user }}"
  authorized_key:
    user: "{{ deploy_user }}"
    key: "{{ deploy_user_sshkey }}"
    state: present

- name: "Add deployer group to sudoers"
  template:
    src: conf/sudoers
    dest: /etc/sudoers.d/sudoers
    mode: u=r,g=r

- name: "Disallow SSH password authentication"
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: Restart ssh

- name: "Disallow SSH root access"
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify: Restart ssh
