---
- name: apt update && apt upgrade && apt autoremove
  ansible.builtin.apt:
    update_cache: yes
    upgrade: yes
    autoremove: true
  become: yes

- name: "Reboot (base images may come with old kernel versions"
  delegate_to: localhost
  hetzner.hcloud.server:
    api_token: "{{ hetzner_cloud_token }}"
    name: "{{ hostvars[inventory_hostname].vars.hetzner_name }}"
    state: restarted

- name: Wait for connection
  ansible.builtin.wait_for_connection:
    timeout: 60