- name: "Enable unattended upgrades (1)"
  ansible.builtin.apt:
    name: unattended-upgrades
    state: present
  become: yes

- name: "Enable unattended upgrades (2)"
  template:
    src: conf/auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    mode: u=rw,g=r,o=r
  become: yes